### PR TITLE
Integrate a sidebar and topbar layout

### PR DESCRIPTION
**Pull request by aanish27**
#72 Integrated Sidebar @Raza9798 Please review

### CODE REVIEW

**Comment by Raza9798** [comment]
image

the side bar covers the entire page when we hover over the left side. here are some examples
https://getbootstrap.com/docs/5.3/examples/sidebars/

**Review by Raza9798 — CHANGES_REQUESTED** [review]
sidebar not working properly

**Comment by aanish27** [comment]
> image
> 
> the side bar covers the entire page when we hover over the left side. here are some examples https://getbootstrap.com/docs/5.3/examples/sidebars/

Sorry couldn't understand can you clear it a bit.....did u mean sidebar width:100vw? 
https://github.com/user-attachments/assets/78ba6646-166c-4f74-ac43-3ce19cb9bbbe

**Comment by Raza9798** [comment]
> > image
> > the side bar covers the entire page when we hover over the left side. here are some examples https://getbootstrap.com/docs/5.3/examples/sidebars/
> 
> Sorry couldn't understand can you clear it a bit.....did u mean sidebar width:100vw? @Raza9798 #72 https://github.com/user-attachments/assets/78ba6646-166c-4f74-ac43-3ce19cb9bbbe

take a look at how does the sidebar behaviors and styles and implement a sidebar like that 
http://preview.themeforest.net/item/myadmin-bootstrap-admin-template/full_screen_preview/15948900?_ga=2.102617985.1876676645.1728512905-779512794.1718221810&_gac=1.58474968.1728571343.CjwKCAjw9p24BhB_EiwA8ID5BuNtQGTh6wNaEfYRmcc8n1OamZfJdbNS--HHKs5YjFWyIVdrZw_pMhoCrcQQAvD_BwE

**Comment by aanish27** [comment]
> > > image
> > > the side bar covers the entire page when we hover over the left side. here are some examples https://getbootstrap.com/docs/5.3/examples/sidebars/
> > 
> > 
> > Sorry couldn't understand can you clear it a bit.....did u mean sidebar width:100vw? @Raza9798 #72 https://github.com/user-attachments/assets/78ba6646-166c-4f74-ac43-3ce19cb9bbbe
> 
> take a look at how does the sidebar behaviors and styles and implement a sidebar like that http://preview.themeforest.net/item/myadmin-bootstrap-admin-template/full_screen_preview/15948900?_ga=2.102617985.1876676645.1728512905-779512794.1718221810&_gac=1.58474968.1728571343.CjwKCAjw9p24BhB_EiwA8ID5BuNtQGTh6wNaEfYRmcc8n1OamZfJdbNS--HHKs5YjFWyIVdrZw_pMhoCrcQQAvD_BwE

Sure got it...

**Comment by aanish27** [comment]
> image
> 
> the side bar covers the entire page when we hover over the left side. here are some examples https://getbootstrap.com/docs/5.3/examples/sidebars/

Fixed Please review again #72 @Raza9798

**Comment by Raza9798** [comment]
there are responsive issue and not appearing as expected. please make a layout like following
image

in the center part the contents should be dynamically rendered.
refer the site : https://adminlte.io/themes/v3/

**Comment by aanish27** [comment]
> there are responsive issue and not appearing as expected. please make a layout like following image
> 
> in the center part the contents should be dynamically rendered. refer the site : https://adminlte.io/themes/v3/

made the layout like the above please review again @Raza9798 

image

**Comment by Raza9798** [comment]
improve more it should be user-friendly and nice look.

see following examples
image

image

image

**Comment by aanish27** [comment]
> improve more it should be user-friendly and nice look.
> 
> see following examples image
> 
> image
> 
> image

@Raza9798 #72

**Comment by aanish27** [comment]
> > improve more it should be user-friendly and nice look.
> > see following examples ![image](https://private-user-images.githubusercontent.com/59387235/375560682-965e8f4a-a2a2-
> as requested more user friendly sidebar implemented using a template please review again @Raza9798 #72

**Comment by Raza9798** [comment]
image

Please use labels on Hover over the menu. UI need more improvements

**Comment by aanish27** [comment]
> Please use labels on Hover over the menu. sidebar UI need more improvements

Implemented please review again @Raza9798 #72

**Comment by Raza9798** [comment]
image

sidebar should be like above image when it is expended. compare with your current design below and improve it. I requested you to integrate the bootstrap sidebar example.

image

**Comment by aanish27** [comment]
> I requested you to integrate the bootstrap sidebar example. remove the additional file you created to manage the styles of sidebar
> 
> that file came with the template...they have changed the navbar to sidebar as there is not sidebar component in bootstrap @Raza9798 #72

**Comment by Raza9798** [comment]
> I requested you to integrate the bootstrap sidebar example. remove the additional file you created to manage the styles of sidebar
> 
> that file came with the template...they have changed the navbar to sidebar as there is not sidebar component in bootstrap @Raza9798 #72

https://getbootstrap.com/docs/5.3/examples/sidebars/# please use this example to implement it

**Comment by aanish27** [comment]
> > I requested you to integrate the bootstrap sidebar example. remove the additional file you created to manage the styles of sidebar
> > that file came with the template...they have changed the navbar to sidebar as there is not sidebar component in bootstrap @Raza9798 #72
> 
> https://getbootstrap.com/docs/5.3/examples/sidebars/# please use this example to implement it

Sure now only found the source code for this example ill implement and let you know @Raza9798

**Comment by aanish27** [comment]
i have implemented the bootstrap example.....you mentioned can you please check whether the way i have implemented is correct after that ill make the UI element changes @Raza9798 #72

**Pull request merged**
